### ISSUE TITLE
Compose January Newsletter Blast for January Speaker

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/governance#2]
Compose newsletter copy for Email Blast first week of January announcing the new year and upcoming speaker session January 21st.

**Comment by nikolajbaer** [comment]
Key things:

1. Happy New Year
2. Recap of what is happening at Open San Diego
   - MealsCount Status
   - Voters Voice Status
3. Join Us! January 21st speaker from the City (Colin Santulli - technology program manager of the city's sustainability department) and discussion with UCSD Young Planners student group
4. Get Involved - We are meeting consistently Every Week on Tuesday at Softstack Factory!

Google Doc for copy:

https://docs.google.com/document/d/17AhYZpLCJ6ew6eqMd9CWp9BFBSbGofXvPPFAFekqLc0/edit?folder=0AAOiFBvBrsUYUk9PVA

Additional Subtasks:
 - [ ] Get ahold of Mailchimp Login (in airtable as mailchimp 2)
 - [ ] Confirm Deploy Date : Thursday, January 3rd

**Comment by tommy-stone** [comment]
Nikolaj sent out email in January.
